export const SET_VOTE_FORM = 'SET_VOTE_FORM'
export const SET_VOTE_PLACES = 'SET_VOTE_PLACES'
export const SET_VOTE_IS_LOADING = 'SET_VOTE_IS_LOADING'
export const SET_VOTE_ERROR_MESSAGE = 'SET_VOTE_ERROR_MESSAGE'
