export const SET_RESTAURANT_DETAIL_FORM = 'SET_RESTAURANT_DETAIL_FORM'
export const SET_RESTAURANT_DETAIL_LOADING = 'SET_RESTAURANT_DETAIL_LOADING'
export const SET_RESTAURANT_DETAIL_MESSAGE = 'SET_RESTAURANT_DETAIL_MESSAGE'
