export const SET_VOTE_DETAIL_UPDATE = 'SET_VOTE_DETAIL_UPDATE'
export const SET_VOTE_DETAIL_UPDATE_VOTE = 'SET_VOTE_DETAIL_UPDATE_VOTE'
export const ADD_VOTE_DETAIL_UPDATE_PLACEID = 'ADD_VOTE_DETAIL_UPDATE_PLACEID'
export const DELETE_VOTE_DETAIL_UPDATE_VOTE_ALL = 'DELETE_VOTE_DETAIL_UPDATE_VOTE_ALL'
