export const SET_EXAMPLE_NEWS = 'SET_EXAMPLE_NEWS'
export const SET_EXAMPLE_IS_LOADING = 'SET_EXAMPLE_IS_LOADING'
export const SET_EXAMPLE_ERROR_MESSAGE = 'SET_EXAMPLE_ERROR_MESSAGE'
export const INCREASE_EXAMPLE_COUNT = 'INCREASE_EXAMPLE_COUNT'
