export const SELECT_EXMAPLE_NEWS = 'SELECT_EXAMPL_NEWS'
export const GET_EXMAPLE_NEWS = 'GET_EXAMPL_NEWS'
export const SET_EXMAPLE_NEWS = 'SET_EXAMPL_NEWS'

export const INCREASE_EXMAPLE_COUNT = 'INCREASE_EXMAPLE_COUNT'
