export const SET_VOTE_DETAIL_INIT = 'SET_VOTE_DETAIL_INIT'

export const SET_VOTE_DETAIL_VOTE = 'SET_VOTE_DETAIL_VOTE'

export const SET_VOTE_DETAIL_IS_VOTE_DONE = 'SET_VOTE_DETAIL_IS_VOTE_DONE'
export const SET_VOTE_DETAIL_IS_VOTE_END = 'SET_VOTE_DETAIL_IS_VOTE_END'
export const SET_VOTE_DETAIL_VOTE_PLACE_IDS = 'SET_VOTE_DETAIL_VOTE_PLACE_IDS'

export const SET_VOTE_DETAIL_VOTE_PLACE_IDS_FORM = 'SET_VOTE_DETAIL_VOTE_PLACE_IDS_FORM'
export const SET_VOTE_DETAIL_VOTE_PLACE_ID_FORM = 'SET_VOTE_DETAIL_VOTE_PLACE_ID_FORM'
export const DELETE_VOTE_DETAIL_VOTE_PLACE_ID_FORM = 'DELETE_VOTE_DETAIL_VOTE_PLACE_ID_FORM'

export const SET_VOTE_DETAIL_IS_LOADING = 'SET_VOTE_DETAIL_IS_LOADING'
export const SET_VOTE_DETAIL_ERROR_MESSAGE = 'SET_VOTE_DETAIL_ERROR_MESSAGE'
